//! The component registry: the per-type reflection table that drives serialize /
//! deserialize, `add-component` / `remove-component`, `present_component_names`, and the
//! component-order logic.
//!
//! [`ComponentTraits`] is a struct of plain `fn` pointers — a hand-rolled Go-interface
//! itable synthesized once per type by the generic [`ComponentRegistry::register`]. Each
//! fn-pointer is monomorphic over `C` and captures nothing (no `Box<dyn Fn>` allocation).
//! The join key is [`TypeId::of::<C>`](std::any::TypeId) — Rust's stable in-process type
//! identity.
//!
//! The registry exists purely for serialize / deserialize / has / add / remove / copy +
//! name / removable; the inspector is the React editor, so there is no per-type draw hook.
//!
//! [`serialize_entity`](ComponentRegistry::serialize_entity) walks the registry rows and
//! asks each `has(scene, entity)`, emitting `{ name: serialize(...) }` for every present
//! row. This avoids reliance on an ECS storage-introspection API `hecs` does not expose.

use std::any::TypeId;
use std::collections::{HashMap, HashSet};

use serde_json::{Map, Value};

use crate::component::{
    AnimationPlayer, Bone, BonePhysicsComponent, Camera, CharacterController, Collider,
    ComponentOrder, DirectionalLight, FootIk, KinematicBones, Material, MaterialAsset, MaterialSet,
    Mesh, ModelInstance, Name, PointLight, ReflectionProbe, Relationship, Rigidbody, Script,
    SkinnedMesh, SpotLight, Transform,
};
use crate::error::Result;
use crate::scene::{Component, Entity, Scene};

/// A component's JSON serde, the per-type bodies the registry trampolines dispatch to.
///
/// Expressing the `to_json` / `from_json` pair as a trait lets the registry's stored
/// fn-pointers call `C::to_json` / `C::from_json` directly while staying capture-free `fn`
/// pointers (a closure capturing a per-type fn is not a `fn` pointer).
///
/// The byte-compatible per-component bodies live in `serde.rs` — one `impl` per built-in
/// component. The default bodies here are the inert fallback (emit `null`, leave the
/// component unchanged) for any type that satisfies the bound without a real body, e.g. a
/// test-only component.
pub trait SceneSerialize {
    /// Serializes this component to its JSON value.
    fn to_json(&self) -> Value {
        Value::Null
    }

    /// Fills this component in place from its JSON value.
    ///
    /// # Errors
    ///
    /// A malformed value yields a [`crate::Error`]; the default body never fails.
    fn load_json(&mut self, value: &Value) -> Result<()> {
        let _ = value;
        Ok(())
    }
}

/// The per-type reflection record — a struct of monomorphic fn-pointers, one row per
/// registered component type.
///
/// The fn-pointers carry no captured state (each is generated by a single generic
/// [`ComponentRegistry::register`] call closing over the component type), so the whole
/// table is `Copy` and cheap to walk. `name` is the stable JSON key and UI header (e.g.
/// `"Transform"`); `removable` gates whether the editor's `remove-component` accepts it
/// (the durable `Name` / `Transform` / `Relationship` rows are non-removable).
#[derive(Clone, Copy)]
pub struct ComponentTraits {
    /// The stable JSON key and UI header, e.g. `"Transform"`.
    pub name: &'static str,
    /// Whether the editor may remove this component from an entity.
    pub removable: bool,
    /// Whether `entity` carries this component.
    pub has: fn(&Scene, Entity) -> bool,
    /// Default-constructs this component onto `entity`.
    pub add_default: fn(&mut Scene, Entity),
    /// Removes this component from `entity` if present.
    pub remove: fn(&mut Scene, Entity),
    /// Clones this component from `(src, from)` onto `(dst, to)` when present on the
    /// source.
    pub copy_to: fn(&Scene, Entity, &mut Scene, Entity),
    /// Serializes `entity`'s component to JSON, dispatching to the type's
    /// [`SceneSerialize::to_json`].
    pub serialize: fn(&Scene, Entity) -> Value,
    /// Default-constructs the component if absent, then deserializes JSON into it,
    /// dispatching to the type's [`SceneSerialize::load_json`].
    pub deserialize: fn(&mut Scene, Entity, &Value) -> Result<()>,
}

/// The component reflection table: the rows plus the `TypeId` / name indices.
///
/// Built once by [`register_builtin_components`] (the single registration site). The
/// row order is the registration order; the document-level component order is owned by
/// [`ComponentOrder`] and reconciled by [`ComponentRegistry::component_order`], so the
/// emit order of [`ComponentRegistry::serialize_entity`] is incidental.
#[derive(Default)]
pub struct ComponentRegistry {
    rows: Vec<ComponentTraits>,
    by_id: HashMap<TypeId, usize>,
    by_name: HashMap<&'static str, usize>,
}

impl ComponentRegistry {
    /// An empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers a component type `C` once, synthesizing the structural fn-pointers
    /// (`has` / `add_default` / `remove` / `copy_to`) from the generic component access and
    /// taking the already-built JSON serde trampolines as two fn-pointers.
    ///
    /// This is the low-level primitive the [`register_component!`](crate::register_component)
    /// macro expands to — the macro is the one-line registration *surface*, building the
    /// `serialize` / `deserialize` trampolines from the supplied `to_json` / `from_json`
    /// paths so the serde is spelled out at the registration site. `register` keeps the
    /// trampolines as bare `fn` pointers (no capture), so [`ComponentTraits`] stays `Copy`.
    ///
    /// Adding a component type is a single macro line — there is no per-type hand-written
    /// trait struct. The `TypeId::of::<C>()` is the join key; the name is the stable JSON
    /// key. A second registration under the same name or type overwrites the index (the
    /// single registration site never does this — the completeness test guards it).
    pub fn register<C: Component + Default + Clone>(
        &mut self,
        name: &'static str,
        removable: bool,
        serialize: fn(&Scene, Entity) -> Value,
        deserialize: fn(&mut Scene, Entity, &Value) -> Result<()>,
    ) {
        let index = self.rows.len();
        let traits = ComponentTraits {
            name,
            removable,
            has: |scene, entity| scene.has_component::<C>(entity),
            add_default: |scene, entity| {
                let _ = scene.add_component(entity, C::default());
            },
            remove: |scene, entity| scene.remove_component::<C>(entity),
            copy_to: |src, from, dst, to| {
                if let Ok(value) = src.with_component::<C, _>(from, Clone::clone) {
                    let _ = dst.add_component(to, value);
                }
            },
            serialize,
            deserialize,
        };
        self.by_id.insert(TypeId::of::<C>(), index);
        self.by_name.insert(name, index);
        self.rows.push(traits);
    }

    /// All registered rows, in registration order.
    #[must_use]
    pub fn rows(&self) -> &[ComponentTraits] {
        &self.rows
    }

    /// The row for component type `C`, or `None` if it is unregistered.
    #[must_use]
    pub fn find_by_type<C: Component>(&self) -> Option<&ComponentTraits> {
        self.by_id.get(&TypeId::of::<C>()).map(|&i| &self.rows[i])
    }

    /// The row for the runtime `TypeId`, or `None`.
    #[must_use]
    pub fn find_by_id(&self, id: TypeId) -> Option<&ComponentTraits> {
        self.by_id.get(&id).map(|&i| &self.rows[i])
    }

    /// The row for a component name, or `None`.
    #[must_use]
    pub fn find_by_name(&self, name: &str) -> Option<&ComponentTraits> {
        self.by_name.get(name).map(|&i| &self.rows[i])
    }

    /// The names of every registered component present on `entity`, excluding
    /// `Relationship` and `Bone`.
    ///
    /// `Relationship` is edited through reparenting, not as a panel row; `Bone` is an
    /// import-set marker — neither belongs in the inspector's component list nor the
    /// authored component order.
    #[must_use]
    pub fn present_component_names(&self, scene: &Scene, entity: Entity) -> Vec<String> {
        self.rows
            .iter()
            .filter(|t| t.name != "Relationship" && t.name != "Bone" && (t.has)(scene, entity))
            .map(|t| t.name.to_string())
            .collect()
    }

    /// The canonical component order: [`Self::present_component_names`].
    #[must_use]
    pub fn canonical_component_order(&self, scene: &Scene, entity: Entity) -> Vec<String> {
        self.present_component_names(scene, entity)
    }

    /// The reconciled, stored component order for `entity`.
    ///
    /// Drops names no longer present, dedups, then appends any present-but-unordered names
    /// in canonical order. Seeds a default [`ComponentOrder`] if the entity lacks one, then
    /// writes the reconciled order back and returns it.
    pub fn component_order(&self, scene: &mut Scene, entity: Entity) -> Vec<String> {
        self.ensure_order(scene, entity);
        let canonical = self.canonical_component_order(scene, entity);
        let present: HashSet<&str> = canonical.iter().map(String::as_str).collect();

        let stored = scene
            .with_component::<ComponentOrder, _>(entity, |o| o.names.clone())
            .unwrap_or_default();

        let mut kept: HashSet<String> = HashSet::new();
        let mut next: Vec<String> = Vec::with_capacity(canonical.len());
        for name in stored {
            if present.contains(name.as_str()) && !kept.contains(&name) {
                kept.insert(name.clone());
                next.push(name);
            }
        }
        for name in &canonical {
            if !kept.contains(name) {
                next.push(name.clone());
            }
        }

        let result = next.clone();
        let _ = scene.with_component_mut::<ComponentOrder, _>(entity, |o| o.names = next);
        result
    }

    /// Replaces the stored component order for `entity`.
    ///
    /// # Errors
    ///
    /// [`Error::ComponentOrder`](crate::Error::ComponentOrder) when `names` is not exactly
    /// the present set: wrong length, a non-present name, or a duplicate.
    pub fn set_component_order(
        &self,
        scene: &mut Scene,
        entity: Entity,
        names: Vec<String>,
    ) -> Result<()> {
        let canonical = self.canonical_component_order(scene, entity);
        let present: HashSet<&str> = canonical.iter().map(String::as_str).collect();
        if names.len() != canonical.len() {
            return Err(crate::Error::ComponentOrder(format!(
                "component order must contain {} entries",
                canonical.len()
            )));
        }
        let mut seen: HashSet<&str> = HashSet::new();
        for name in &names {
            if !present.contains(name.as_str()) {
                return Err(crate::Error::ComponentOrder(format!(
                    "component order contains non-present component '{name}'"
                )));
            }
            if !seen.insert(name.as_str()) {
                return Err(crate::Error::ComponentOrder(format!(
                    "component order contains duplicate component '{name}'"
                )));
            }
        }
        self.ensure_order(scene, entity);
        let _ = scene.with_component_mut::<ComponentOrder, _>(entity, |o| o.names = names);
        Ok(())
    }

    /// Moves `name` to the end of the reconciled order.
    ///
    /// Reconciles like [`Self::component_order`] but drops `name` from the body, then
    /// appends it last when it is present.
    pub fn append_component_order(&self, scene: &mut Scene, entity: Entity, name: &str) {
        self.ensure_order(scene, entity);
        let canonical = self.canonical_component_order(scene, entity);
        let present: HashSet<&str> = canonical.iter().map(String::as_str).collect();
        let stored = scene
            .with_component::<ComponentOrder, _>(entity, |o| o.names.clone())
            .unwrap_or_default();

        let mut kept: HashSet<String> = HashSet::new();
        let mut next: Vec<String> = Vec::with_capacity(canonical.len());
        for item in stored {
            if item != name && present.contains(item.as_str()) && !kept.contains(&item) {
                kept.insert(item.clone());
                next.push(item);
            }
        }
        for item in &canonical {
            if item != name && !kept.contains(item) {
                kept.insert(item.clone());
                next.push(item.clone());
            }
        }
        if present.contains(name) {
            next.push(name.to_string());
        }
        let _ = scene.with_component_mut::<ComponentOrder, _>(entity, |o| o.names = next);
    }

    /// Erases `name` from the stored order, then reconciles.
    pub fn remove_component_order(&self, scene: &mut Scene, entity: Entity, name: &str) {
        self.ensure_order(scene, entity);
        let _ = scene.with_component_mut::<ComponentOrder, _>(entity, |o| {
            o.names.retain(|n| n != name);
        });
        let _ = self.component_order(scene, entity);
    }

    /// Resets the stored order to the canonical order.
    pub fn sort_component_order(&self, scene: &mut Scene, entity: Entity) {
        self.ensure_order(scene, entity);
        let canonical = self.canonical_component_order(scene, entity);
        let _ = scene.with_component_mut::<ComponentOrder, _>(entity, |o| o.names = canonical);
    }

    /// Seeds a default [`ComponentOrder`] onto `entity` if it lacks one.
    fn ensure_order(&self, scene: &mut Scene, entity: Entity) {
        if !scene.has_component::<ComponentOrder>(entity) {
            let _ = scene.add_component(entity, ComponentOrder::default());
        }
    }

    /// Serializes every present registered component of `entity` to a
    /// `{ name: value }` object.
    ///
    /// Walks the registry rows and emits a key for each row whose `has` reports present —
    /// no ECS storage introspection. Unregistered components
    /// (`IdComponent` / `WorldTransform` / `PoseOverride` / `ComponentOrder`) are absent;
    /// the document assembler writes `id` and `componentOrder` separately.
    #[must_use]
    pub fn serialize_entity(&self, scene: &Scene, entity: Entity) -> Value {
        let mut components = Map::new();
        for traits in &self.rows {
            if (traits.has)(scene, entity) {
                components.insert(traits.name.to_string(), (traits.serialize)(scene, entity));
            }
        }
        Value::Object(components)
    }

    /// Deserializes a `{ name: value }` object onto `entity`, default-constructing each
    /// named component then filling it.
    ///
    /// An unknown component name warns and is skipped (a forward-compat document may carry
    /// a component this build does not register). A failed body short-circuits with the
    /// offending name in the error.
    ///
    /// # Errors
    ///
    /// [`Error::Deserialize`](crate::Error::Deserialize) when a component body fails, or
    /// [`Error::Json`](crate::Error::Json) when `components` is not a JSON object.
    pub fn deserialize_entity(
        &self,
        scene: &mut Scene,
        entity: Entity,
        components: &Value,
    ) -> Result<()> {
        let object = components
            .as_object()
            .ok_or_else(|| crate::Error::Json("entity components must be a JSON object".into()))?;
        for (name, value) in object {
            let Some(&index) = self.by_name.get(name.as_str()) else {
                saffron_core::log_warn!("unknown component '{name}', skipping");
                continue;
            };
            let deserialize = self.rows[index].deserialize;
            deserialize(scene, entity, value)
                .map_err(|e| crate::Error::Deserialize(format!("{name}: {e}")))?;
        }
        Ok(())
    }
}

/// Registers all built-in serialized component types onto a fresh registry — the single
/// registration site.
///
/// Adding a serialized component is one line here and nothing else; the
/// `registry_is_complete` test guards against a missed registration.
/// The runtime-only components (`IdComponent`, `WorldTransform`, `PoseOverride`,
/// `ComponentOrder`, and the `Relationship` / `SkinnedMesh` runtime caches) are absent by
/// design: they never serialize through a registry row.
///
/// The serde bodies are phase-6 placeholders ([`SceneSerialize`]'s defaults); the
/// registration shape and the row set are this phase's deliverable.
#[must_use]
pub fn register_builtin_components() -> ComponentRegistry {
    let mut reg = ComponentRegistry::new();

    register_component!(reg, Name, "Name", false);
    register_component!(reg, Transform, "Transform", false);
    register_component!(reg, Mesh, "Mesh");
    register_component!(reg, Camera, "Camera");
    register_component!(reg, Material, "Material");
    register_component!(reg, MaterialSet, "MaterialSet");
    register_component!(reg, MaterialAsset, "MaterialAsset");
    register_component!(reg, ModelInstance, "ModelInstance");
    register_component!(reg, Script, "Script");
    register_component!(reg, AnimationPlayer, "AnimationPlayer");
    register_component!(reg, DirectionalLight, "DirectionalLight");
    register_component!(reg, PointLight, "PointLight");
    register_component!(reg, SpotLight, "SpotLight");
    register_component!(reg, ReflectionProbe, "ReflectionProbe");
    register_component!(reg, Relationship, "Relationship", false);
    register_component!(reg, SkinnedMesh, "SkinnedMesh");
    register_component!(reg, Bone, "Bone");
    register_component!(reg, FootIk, "FootIk");
    register_component!(reg, BonePhysicsComponent, "BonePhysics");
    register_component!(reg, Rigidbody, "Rigidbody");
    register_component!(reg, Collider, "Collider");
    register_component!(reg, KinematicBones, "KinematicBones");
    register_component!(reg, CharacterController, "CharacterController");

    reg
}

/// The component types that serialize through a registry row — the canonical built-in set.
///
/// Used by the `registry_is_complete` test: every name here must resolve a row, and every
/// row must appear here. Adding a serialized component means adding it to
/// [`register_builtin_components`] and to this list together.
pub const BUILTIN_COMPONENT_NAMES: &[&str] = &[
    "Name",
    "Transform",
    "Mesh",
    "Camera",
    "Material",
    "MaterialSet",
    "MaterialAsset",
    "ModelInstance",
    "Script",
    "AnimationPlayer",
    "DirectionalLight",
    "PointLight",
    "SpotLight",
    "ReflectionProbe",
    "Relationship",
    "SkinnedMesh",
    "Bone",
    "FootIk",
    "BonePhysics",
    "Rigidbody",
    "Collider",
    "KinematicBones",
    "CharacterController",
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::component::IdComponent;

    fn registry() -> ComponentRegistry {
        register_builtin_components()
    }

    /// A round-trip through the registry: a registered type resolves by name and by type,
    /// and `present_component_names` filters `Relationship` and `Bone`.
    #[test]
    fn registration_resolves_by_name_and_type_and_filters() {
        let reg = registry();

        // find_by_name / find_by_type resolve the same row.
        let transform = reg.find_by_name("Transform").expect("Transform registered");
        assert_eq!(transform.name, "Transform");
        assert!(!transform.removable, "Transform is non-removable");
        let by_type = reg
            .find_by_type::<Transform>()
            .expect("Transform by TypeId");
        assert_eq!(by_type.name, transform.name);

        // An unregistered runtime-only type resolves nothing.
        assert!(reg.find_by_type::<IdComponent>().is_none());
        assert!(reg.find_by_name("WorldTransform").is_none());

        // present_component_names drops Relationship and Bone but keeps the rest.
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        scene.add_component(e, Bone::default()).unwrap();
        scene.add_component(e, Camera::default()).unwrap();
        let present = reg.present_component_names(&scene, e);
        assert!(present.contains(&"Name".to_string()));
        assert!(present.contains(&"Transform".to_string()));
        assert!(present.contains(&"Camera".to_string()));
        assert!(
            !present.contains(&"Relationship".to_string()),
            "Relationship filtered"
        );
        assert!(!present.contains(&"Bone".to_string()), "Bone filtered");
    }

    /// `set_component_order` rejects a wrong-length, a non-present, and a duplicate list,
    /// and accepts an exact permutation of the present set.
    #[test]
    fn set_component_order_validates_against_present_set() {
        let reg = registry();
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        scene.add_component(e, Camera::default()).unwrap();
        // Present (filtered) set is exactly {Name, Transform, Camera}.
        let canonical = reg.canonical_component_order(&scene, e);
        assert_eq!(canonical.len(), 3);

        // Wrong length.
        assert!(matches!(
            reg.set_component_order(&mut scene, e, vec!["Name".into(), "Transform".into()]),
            Err(crate::Error::ComponentOrder(_))
        ));
        // Non-present name (right length).
        assert!(matches!(
            reg.set_component_order(
                &mut scene,
                e,
                vec!["Name".into(), "Transform".into(), "Mesh".into()]
            ),
            Err(crate::Error::ComponentOrder(_))
        ));
        // Duplicate.
        assert!(matches!(
            reg.set_component_order(
                &mut scene,
                e,
                vec!["Name".into(), "Name".into(), "Camera".into()]
            ),
            Err(crate::Error::ComponentOrder(_))
        ));
        // A valid permutation is accepted and stored.
        let order = vec!["Camera".into(), "Name".into(), "Transform".into()];
        reg.set_component_order(&mut scene, e, order.clone())
            .unwrap();
        let stored = scene
            .with_component::<ComponentOrder, _>(e, |o| o.names.clone())
            .unwrap();
        assert_eq!(stored, order);
    }

    /// `component_order` reconciles a stale stored order against the present set: a removed
    /// component drops out, a new component appends, and a duplicate dedups.
    #[test]
    fn component_order_reconciles_stale_against_present() {
        let reg = registry();
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        scene.add_component(e, Camera::default()).unwrap();

        // A hand-poked stale order: a removed component (Mesh, absent), a duplicate (Name),
        // and the present Camera missing — Transform is present but unordered.
        scene
            .with_component_mut::<ComponentOrder, _>(e, |o| {
                o.names = vec!["Name".into(), "Mesh".into(), "Name".into()];
            })
            .unwrap();

        let order = reg.component_order(&mut scene, e);
        // Mesh dropped (absent), Name deduped to one, Transform + Camera appended in
        // canonical order.
        assert_eq!(order, vec!["Name", "Transform", "Camera"]);

        // sort_component_order resets straight to canonical.
        reg.sort_component_order(&mut scene, e);
        let sorted = scene
            .with_component::<ComponentOrder, _>(e, |o| o.names.clone())
            .unwrap();
        assert_eq!(sorted, reg.canonical_component_order(&scene, e));
    }

    /// `append_component_order` moves a name to the end while keeping the rest reconciled.
    #[test]
    fn append_component_order_moves_name_last() {
        let reg = registry();
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        scene.add_component(e, Camera::default()).unwrap();
        reg.sort_component_order(&mut scene, e);

        reg.append_component_order(&mut scene, e, "Name");
        let order = scene
            .with_component::<ComponentOrder, _>(e, |o| o.names.clone())
            .unwrap();
        assert_eq!(order.last().map(String::as_str), Some("Name"));
        assert_eq!(order.len(), 3);
    }

    /// `serialize_entity` walks rows (not ECS storage): a present registered component
    /// emits a key; unregistered runtime-only components are absent.
    #[test]
    fn serialize_entity_walks_rows_and_skips_unregistered() {
        let reg = registry();
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        scene.add_component(e, Camera::default()).unwrap();
        // Add an unregistered runtime-only component; it must not appear.
        scene
            .add_component(e, crate::component::WorldTransform::default())
            .unwrap();
        scene
            .add_component(e, crate::component::PoseOverride::default())
            .unwrap();

        let value = reg.serialize_entity(&scene, e);
        let object = value.as_object().expect("entity serializes to an object");

        // Present registered components are keys.
        assert!(object.contains_key("Name"));
        assert!(object.contains_key("Transform"));
        assert!(object.contains_key("Camera"));
        assert!(object.contains_key("Relationship"));

        // Unregistered components are absent: having no registry row, the row walk never
        // sees them.
        assert!(!object.contains_key("WorldTransform"));
        assert!(!object.contains_key("PoseOverride"));
        assert!(!object.contains_key("Id"));
        assert!(!object.contains_key("ComponentOrder"));
    }

    /// `deserialize_entity` default-constructs each named component and warns past an
    /// unknown name without failing.
    #[test]
    fn deserialize_entity_adds_named_and_skips_unknown() {
        let reg = registry();
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        assert!(!scene.has_component::<Camera>(e));

        let doc = serde_json::json!({
            "Camera": {},
            "PointLight": {},
            "NotARealComponent": { "x": 1 },
        });
        reg.deserialize_entity(&mut scene, e, &doc).unwrap();
        assert!(scene.has_component::<Camera>(e), "Camera default-added");
        assert!(
            scene.has_component::<PointLight>(e),
            "PointLight default-added"
        );

        // A non-object document is a typed error.
        assert!(matches!(
            reg.deserialize_entity(&mut scene, e, &serde_json::json!(42)),
            Err(crate::Error::Json(_))
        ));
    }

    /// The anti-silent-gap test: every intended serialized component is registered, and the
    /// registry holds no surprise rows. The two lists move together or this fails.
    #[test]
    fn registry_is_complete() {
        let reg = registry();

        // Every intended name resolves a row.
        for &name in BUILTIN_COMPONENT_NAMES {
            assert!(
                reg.find_by_name(name).is_some(),
                "component '{name}' is intended to serialize but is not registered"
            );
        }

        // The registry holds exactly the intended set (no extra rows, no missing rows).
        assert_eq!(
            reg.rows().len(),
            BUILTIN_COMPONENT_NAMES.len(),
            "registry row count must match the intended built-in set"
        );
        let registered: HashSet<&str> = reg.rows().iter().map(|t| t.name).collect();
        let intended: HashSet<&str> = BUILTIN_COMPONENT_NAMES.iter().copied().collect();
        assert_eq!(registered, intended, "registered set == intended set");
    }

    /// `copy_to` clones a present component from one entity to another (across scenes, the
    /// play-duplicate shape) and is a no-op when the source lacks it.
    #[test]
    fn copy_to_clones_present_only() {
        let reg = registry();
        let mut src_scene = Scene::new();
        let src = src_scene.create_entity("src");
        src_scene
            .add_component(
                src,
                Camera {
                    fov: 77.0,
                    ..Camera::default()
                },
            )
            .unwrap();

        // The registry `copy_to` takes two `&mut Scene` (src + dst), the play-duplicate
        // shape; a present component clones across.
        let mut dst_scene = Scene::new();
        let dst = dst_scene.create_entity("dst");
        let camera_row = reg.find_by_name("Camera").unwrap();
        (camera_row.copy_to)(&src_scene, src, &mut dst_scene, dst);
        assert!(dst_scene.has_component::<Camera>(dst));
        assert_eq!(dst_scene.component::<Camera>(dst).unwrap().fov, 77.0);

        // A no-op when the source lacks the component (Mesh, never added).
        let mesh_row = reg.find_by_name("Mesh").unwrap();
        (mesh_row.copy_to)(&src_scene, src, &mut dst_scene, dst);
        assert!(!dst_scene.has_component::<Mesh>(dst));
    }

    // Two test-only stub components registered through the macro with explicit, one-off
    // serde paths (not a `SceneSerialize` impl) — exercising the macro's explicit-serde
    // form, the `removable` default, and a round-trip through the synthesized fn-pointers.

    #[derive(Clone, Default)]
    struct StubA {
        value: u64,
    }

    #[derive(Clone, Default)]
    struct StubB;

    fn stub_a_to_json(c: &StubA) -> Value {
        serde_json::json!({ "value": c.value })
    }

    fn stub_a_from_json(c: &mut StubA, value: &Value) -> Result<()> {
        c.value = value.get("value").and_then(Value::as_u64).unwrap_or(0);
        Ok(())
    }

    fn stub_b_to_json(_c: &StubB) -> Value {
        Value::Null
    }

    fn stub_b_from_json(_c: &mut StubB, _value: &Value) -> Result<()> {
        Ok(())
    }

    /// The macro's explicit-serde form expands to a row carrying the right name, the right
    /// `removable` flag (defaulted vs explicit), and working `has` / `serialize` /
    /// `deserialize` fn-pointers wired to the supplied serde.
    #[test]
    fn register_component_macro_builds_rows_with_explicit_serde() {
        let mut reg = ComponentRegistry::new();
        // StubA: explicit serde, `removable` defaulted to true.
        register_component!(reg, StubA, "StubA", stub_a_to_json, stub_a_from_json);
        // StubB: explicit serde, `removable` explicit false.
        register_component!(reg, StubB, "StubB", stub_b_to_json, stub_b_from_json, false);

        let a = reg.find_by_name("StubA").expect("StubA registered");
        assert_eq!(a.name, "StubA");
        assert!(a.removable, "removable defaults to true");
        let b = reg.find_by_name("StubB").expect("StubB registered");
        assert!(!b.removable, "removable explicit false");

        // The rows resolve by TypeId too (the macro keyed them on `TypeId::of::<C>()`).
        assert!(reg.find_by_type::<StubA>().is_some());
        assert!(reg.find_by_type::<StubB>().is_some());

        // has + serialize round-trip through the synthesized trampolines.
        let mut scene = Scene::new();
        let e = scene.create_entity("e");
        assert!(!(a.has)(&scene, e), "StubA absent before deserialize");

        // deserialize default-constructs then fills via the supplied from_json.
        (a.deserialize)(&mut scene, e, &serde_json::json!({ "value": 42 })).unwrap();
        assert!((a.has)(&scene, e), "StubA present after deserialize");
        let stored = scene.with_component::<StubA, _>(e, |c| c.value).unwrap();
        assert_eq!(stored, 42);

        // serialize dispatches to the supplied to_json.
        assert_eq!((a.serialize)(&scene, e), serde_json::json!({ "value": 42 }));
    }

    /// Registration order is the source-list order — the macro list, deterministic across
    /// builds (the property `inventory` could not guarantee). The row order equals the
    /// `BUILTIN_COMPONENT_NAMES` list order verbatim.
    #[test]
    fn registration_order_equals_source_list_order() {
        let reg = registry();
        let row_names: Vec<&str> = reg.rows().iter().map(|t| t.name).collect();
        assert_eq!(
            row_names, BUILTIN_COMPONENT_NAMES,
            "row order must equal the register_builtin_components / BUILTIN_COMPONENT_NAMES order"
        );

        // Stable across two independent builds of the registry (no link-order dependence).
        let reg2 = registry();
        let row_names2: Vec<&str> = reg2.rows().iter().map(|t| t.name).collect();
        assert_eq!(row_names, row_names2);
    }
}
